CREATE OR REPLACE TABLE fraud_alerts (
    claimid                   VARCHAR,
    beneid                    VARCHAR,
    provider                  VARCHAR,
    claim_type                VARCHAR,
    claimstartdt              DATE,
    claimenddt                DATE,
    inscclaimamtreimbursed    FLOAT,
    deductibleamtpaid         FLOAT,
    attendingphysician        VARCHAR,
    operatingphysician        VARCHAR,
    patient_age               INT,
    chronic_condition_count   INT,
    claim_duration_days       INT,
    los_days                  INT,
    is_fraud                  INT,
    flag_type                 VARCHAR,
    flag_description          VARCHAR,
    risk_score                FLOAT,
    fraud_score               FLOAT,
    flagged_at                TIMESTAMP,
    scored_at                 TIMESTAMP,
    processed_at              TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
